name: Setup application
description: Setup Node.js environment

inputs:
  no-save-cache:
    description: If true, skips save cache behavior. Default is false.
    default: "false"
    required: false

runs:
  using: composite
  steps:
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version-file: .node-version

    - name: Restore Cache
      uses: actions/cache/restore@v3
      id: node-modules-cache-restore
      with:
        path: node_modules
        key: ${{ runner.os }}-nodemodules-${{ hashFiles('**/package-lock.json') }}

    - name: Install dependencies
      if: steps.node-modules-cache-restore.outputs.cache-hit != 'true'
      shell: bash
      run: npm ci

    - name: Save Cache
      if: steps.node-modules-cache-restore.outputs.cache-hit != 'true' && inputs.no-save-cache != 'true'
      uses: actions/cache/save@v3
      with:
        path: node_modules
        key: ${{ steps.node-modules-cache-restore.outputs.cache-primary-key }}
